In [1]:
import numpy as np
import pandas as pd


In [2]:
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv('/Users/shivani/ML_Zoomcamp/01-intro/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# Records count: 9704

In [4]:
df.shape

(9704, 11)

# Fuel types: 2

In [5]:
df['fuel_type'].nunique()

2

# Missing values: 4

In [6]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# Max fuel efficiency: 23.75

In [7]:
df['fuel_efficiency_mpg'].groupby(df['origin']).max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

# Median value of horsepower: No change

In [8]:
#median value of the horsepower
df['horsepower'].median()

149.0

In [9]:
#fill the missing values in the horsepower column with the most frequent value
df['horsepower'].count()

8996

In [10]:
#calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [11]:
df['horsepower'].fillna(df['horsepower'].mode())

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [12]:
df['horsepower'].median()

149.0

## Sum of weights

In [13]:
#Select all the cars from Asia
asia_cars = df[df['origin'] == 'Asia']
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [14]:
# Select only columns vehicle_weight and model_year
asia_cars[['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [15]:
#Select the first 7 values
asia_cars_models = asia_cars[['vehicle_weight', 'model_year']].head(7)
asia_cars_models

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [16]:
# Get the underlying NumPy array. Let's call it X.
X = asia_cars_models.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [17]:
X.shape

(7, 2)

In [ ]:
#Transpose of X
XT = X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [19]:
XT.shape

(2, 7)

In [22]:
#Matrix matrix multiplication

XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [23]:
XTX.shape

(2, 2)

In [24]:
#inverse of XTX

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [25]:
XTX.shape

(2, 2)

In [37]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [30]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

XTX_inv_XT = XTX_inv.dot(XT)
XTX_inv_XT

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [ ]:
XTX_inv_XT.shape

(2, 7)

In [34]:
w = XTX_inv_XT.dot(y)
w

array([0.01386421, 0.5049067 ])

In [38]:
w.sum()

0.5187709081074026